services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "14024:8501"
    volumes:
      - ./frontend:/app # フロントエンドのコードをバインドマウント
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "14124:8000"
    volumes:
      - ./backend:/app # バックエンドのコードをバインドマウント
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
